apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashi-vault
  namespace: openshift-gitops
spec:
  project: default
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.25.0
    helm:
      releaseName: hashicorp
      valueFiles:
        - vault-values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: hashi-vault
